# Generated by Django 3.1 on 2020-08-22 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200818_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 0, 3, 51, 31832, tzinfo=utc), verbose_name='date_published'),
        ),
    ]
